#' Estimating the inverse first-order reliability method (IFORM) environmental contours
#'
#' @description
#' This function estimates the Invserse FORM (IFORM) environmental contours, as proposed in Winterstein et al. (1993)
#' for a given sample data set or a fitted joint distribution of class \code{ht} or \code{wln}.
#' 
#' @param object either a fitted joint distribution of class \code{wln} or \code{ht}, or an existing sample data
#' set containing \code{hs} and \code{tp} as columns. See details.
#' 
#' @param output_rp the required return periods (in years) for the estimated contours.
#' 
#' @param npy the (optional) number of data points per year. This argument is only needed if the input
#' \code{object} is a sample data set.
#' 
#' @param n_point the number of points to output around each contour. The default value is 100.
#' 
#' @param alpha0 the omission factor for the IFORM contours. The default value is 0, meaning no
#' inflation to the estimated contours.
#' 
#' @details
#' The IFORM contour is constructed based on the first-order reliability method (FORM) and 
#' it searches a hypersphere of constant radius to find the maximum response.
#' 
#' The function can be applied to an existing sample set, which can be generated by function \code{\link{sample_jdistr}}
#' or otherwise by importing a CSV file using function \code{\link[data.table]{fread}}. The input sample data
#' object must contain \code{hs} and \code{tp} as columns. The user must also specify the number of points per year
#' \code{npy} and a valid \code{output_rp}, i.e. the maximum \code{output_rp} must be shorter than the total
#' duration of the data set.
#' 
#' Alternatively this function can be applied to a fitted joint distribution object
#' generated by function \code{\link{fit_ht}} or \code{\link{fit_wln}}.  When applied to a \code{ht} object,
#' the estimated contour is a blending between the two conditional models \eqn{Hs|Tp>tp} and \eqn{Tp|Hs>hs} above
#' high thresholds \eqn{tp} and \eqn{hs}, as specified in Heffernan and Tawn (2004).
#' 
#' @return A set of estimated IFORM contours with the specified return periods in the format
#' of a \code{data.table} with \code{rp}, \code{hs}, and \code{tp} as columns.
#'
#' @examples
#' # Estimating IFORM contours based on a fitted model
#' data(ww3_pk)
#' ht = fit_ht(data = ww3_pk, npy = nrow(ww3_pk)/10, margin_thresh_count = 50, dep_thresh_count = 500)
#' ec_ht = estimate_iform(object = ht, output_rp = c(10,100,1000,10000))
#' plot_ec(ec = ec_ht, raw_data = ww3_pk)
#' 
#' # Estimating IFORM contours based on a sample data set
#' data(ww3_ts)
#' ec_data = estimate_iform(object = ww3_ts, output_rp = c(.5, 1, 2), npy = ww3_ts[, .N/10])
#' plot_ec(ec = ec_data, raw_data = ww3_ts)
#' 
#' @references
#' Winterstein, S. R., Ude, T. C., Cornell, C. A., Bjerager, P., Haver, S., 1993. Environmental parameters
#' for extreme variable: Inverse Form with omission factors. In: Proc. 6th Int. Conf. on
#' Structural Safety and Reliability, Innsbruck, Austria.
#' 
#' Heffernan, Janet & A. Tawn, Jonathan. (2004). A Conditional Approach for Multivariate Extreme Values.
#' Journal of the Royal Statistical Society Series B. 66. 497-546. 10.1111/j.1467-9868.2004.02050.x. 
#' 
#' @seealso \code{\link{fit_ht}}, \code{\link{fit_wln}}, \code{\link{sample_jdistr}}, \code{\link{plot_ec}}
#' 
#' @export
estimate_iform = function(
  object, output_rp, npy = NULL, n_point=100, alpha0=0){
  
  if("wln" %in% class(object)){
    
    res = .estimate_iform_from_wln(wln = object, output_rp = output_rp, n_point = n_point, alpha0 = alpha0)
    if(!is.null(npy)){
      warning("Argument npy will be imported from the provided joint distribution object.  The supplied npy is ignored.")
    }
    
  }else if("ht" %in% class(object)){
    
    res = .estimate_iform_from_ht(ht = object, output_rp = output_rp, n_point = n_point, alpha0 = alpha0)
    if(!is.null(npy)){
      warning("Argument npy will be imported from the provided joint distribution object.  The supplied npy is ignored.")
    }
    
  }else if("data.table" %in% class(object)){
    
    if(is.null(npy)){
      stop("Argument npy must be provided for estimating contours from sample data.")
    }else{
      invalid_rp = output_rp[output_rp>object[, .N/npy]]
      if(length(invalid_rp)==length(output_rp)){
        stop("All output_rp values are invalid as they require extrapolation. Consider fitting a joint distribution first.")
      }else if(length(invalid_rp)>=1 & length(invalid_rp)<length(output_rp)){
        warning("Certain output_rp values are ignored as they requires extrapolation. Consider fitting a joint distribution first.") 
      }
      output_rp = setdiff(output_rp, invalid_rp)
    }
    
    res = .estimate_iform_from_sample_data(
      sample_data = object, sample_data_npy = npy,
      output_rp = output_rp, n_point = n_point, alpha0 = alpha0)
    
  }else{
    
    stop("The input object must be of class ht, wln or data.table.")
  }
  
  return(res)
}


# Sub functions -----------------------------------------------------------

.estimate_iform_from_sample_data = function(sample_data, sample_data_npy, output_rp, n_point, alpha0){
  
  
  # Calculate beta and inflate
  prob = 1 - 1/(sample_data_npy*output_rp)
  beta = qnorm(prob)
  beta_star = beta / (sqrt(1-(alpha0^2)))
  
  # Define points
  angle = seq(0, 2*pi, length.out = n_point+1)
  calc = data.table(rp = rep(output_rp, each=n_point+1), angle = angle)
  calc[, u1:=rep(beta_star, each=n_point+1)*cos(angle)]
  calc[, u2:=rep(beta_star, each=n_point+1)*sin(angle)]
  calc[, p1:=pnorm(u1)]
  calc[, p2:=pnorm(u2)]
  calc[, hs:=quantile(sample_data$hs, p1, names = F)]
  
  for(i in 1:calc[, .N]){
    cond_distr_bw = calc[rp==calc[i]$rp, bw.SJ(hs)]
    td_data = sample_data[abs(hs-calc$hs[i])<=cond_distr_bw/2]
    if(td_data[,.N]<.knn){
      td_data = sample_data[sort.list(abs(hs-calc$hs[i]))[1:.knn]]
    }
    calc[i, tp:=quantile(td_data$tp, p2, names = F)]
  }
  
  # Return
  res = calc[, .(rp, hs, tp)]
  return(res)
}


.estimate_iform_from_wln = function(wln, output_rp, n_point, alpha0){
  
  # Calculate beta and inflate
  prob = 1 - 1/(wln$npy*output_rp)
  beta = qnorm(prob)
  beta_star = beta / (sqrt(1-(alpha0^2)))
  
  # Define points
  angle = seq(0, 2*pi, length.out = n_point+1)
  calc = data.table(rp = rep(output_rp, each=n_point+1), angle = angle)
  calc[, u1:=rep(beta_star, each=n_point+1)*cos(angle)]
  calc[, u2:=rep(beta_star, each=n_point+1)*sin(angle)]
  calc[, p1:=pnorm(u1)]
  calc[, p2:=pnorm(u2)]
  calc[, hs:=qweibull(p1, shape=wln$hs$par["shape"], scale=wln$hs$par["scale"])+wln$hs$par["loc"]]
  calc[, m:=wln$tp$par[1] + wln$tp$par[2] * (hs ^ wln$tp$par[3])]
  calc[, v:=wln$tp$par[4] + wln$tp$par[5] * exp(wln$tp$par[6] * hs)]
  calc[, tp:=qlnorm(p2, m, sqrt(v))]
  
  # Return
  res = calc[, .(rp, hs, tp)]
  return(res)
}

.estimate_iform_from_ht = function(ht, output_rp, n_point, alpha0){
  
  p_thresh = ht$margin$p_margin_thresh
  n_exceed = length(ht$margin$hs$emp)*(1-p_thresh)
  
  # Calculate beta and inflate
  prob = 1 - 1/(ht$npy*output_rp)
  beta = qnorm(prob)
  beta_star = beta / (sqrt(1-(alpha0^2)))
  
  # Define points
  angle = seq(0, 2*pi, length.out = n_point+1)
  calc = data.table(rp = rep(output_rp, each=n_point+1), angle = angle)
  calc[, u1:=rep(beta_star, each=n_point+1)*cos(angle)]
  calc[, u2:=rep(beta_star, each=n_point+1)*sin(angle)]
  calc[, p1:=pnorm(u1)]
  calc[, p2:=pnorm(u2)]

  # Estimate hs based on hs model
  calc_hs = calc[p1>ht$dep$p_dep_thresh]
  calc_hs[, hs:=.convert_unif_to_origin(
    unif = p1, p_thresh = p_thresh, gpd_par = ht$margin$hs$par, emp = ht$margin$hs$emp)]

  # Estimate tp based on tp|hs HT model for large hs
  calc_hs[, lap1:=.convert_unif_to_lap(p1)]
  calc_hs[, resid_q:=quantile(ht$dep$hs$resid, p2)]
  calc_hs[,lap2:=ht$dep$hs$par[1]*lap1+resid_q*lap1^ht$dep$hs$par[2]]
  calc_hs[, p_tp:=.convert_lap_to_unif(lap2)]
  calc_hs[, tp:=.convert_unif_to_origin(
    unif = p_tp, p_thresh = p_thresh, gpd_par = ht$margin$tp$par, emp = ht$margin$tp$emp)]

  # Estimate tp based on tp model
  calc_tp = calc[p2>ht$dep$p_dep_thresh]
  calc_tp[, tp:=.convert_unif_to_origin(
    unif = p2, p_thresh = p_thresh, gpd_par = ht$margin$tp$par, emp = ht$margin$tp$emp)]
  
  # Estimate hs based on hs|tp HT model for large tp
  calc_tp[, lap2:=.convert_unif_to_lap(p2)]
  calc_tp[, resid_q:=quantile(ht$dep$tp$resid, p1)]
  calc_tp[,lap1:=ht$dep$tp$par[1]*lap2+resid_q*lap2^ht$dep$tp$par[2]]
  calc_tp[, p_hs:=.convert_lap_to_unif(lap1)]
  calc_tp[, hs:=.convert_unif_to_origin(
    unif = p_hs, p_thresh = p_thresh, gpd_par = ht$margin$hs$par, emp = ht$margin$hs$emp)]
  
  # Return
  res = merge(
    x = calc_hs[, .(rp, angle, hs, tp)], y = calc_tp[, .(rp, angle, hs, tp)],
    by=c("rp", "angle"), all=T)
  res[is.na(hs.x), hs:=hs.y]
  res[is.na(tp.x), tp:=tp.y]
  res[is.na(hs.y), hs:=hs.x]
  res[is.na(tp.y), tp:=tp.x]
  res[!is.na(hs.x+hs.y), hs:=hs.x*cos(angle)^2+hs.y*sin(angle)^2]
  res[!is.na(hs.x+hs.y), tp:=tp.x*cos(angle)^2+tp.y*sin(angle)^2]
  setkey(res, rp, angle)
  return(res[, .(rp, hs, tp)])
}


